# Generated by Django 5.2.11 on 2026-02-14 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANEJAMENTO', 'Planejamento'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='PLANEJAMENTO', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_prevista_conclusao', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='clients.cliente')),
                ('subscritor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='subscriptions.subscritor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
