# Generated by Django 5.2.11 on 2026-02-15 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_cliente_require_projeto'),
        ('projects', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='ultima_sicronizacao',
        ),
        migrations.AddField(
            model_name='agenda',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='projects.projeto'),
        ),
        migrations.CreateModel(
            name='GoogleCalendarChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('resource_id', models.CharField(max_length=255)),
                ('google_calendar_id', models.CharField(max_length=255)),
                ('expiration', models.DateTimeField()),
                ('sync_token', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('subscritor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_channels', to='subscriptions.subscritor')),
            ],
            options={
                'verbose_name': 'Canal Google Calendar',
                'verbose_name_plural': 'Canais Google Calendar',
            },
        ),
    ]
