# Generated by Django 5.2.11 on 2026-02-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_agenda_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='local',
        ),
    ]
