# Generated by Django 5.2.11 on 2026-02-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='user',
            name='custo_horario_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Custo horário padrão'),
        ),
        migrations.AddField(
            model_name='user',
            name='logo_empresa',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome completo'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('professor', 'Professor')], default='professor', max_length=20, verbose_name='Papel'),
        ),
    ]
